// APEX Financial Empire — Internal Resource Library data
// type: 'video' | 'pdf' | 'training' | 'guide' | 'course'
window.APEX_RESOURCES = [
  {
    id: "phone-sales-mastery",
    type: "course",
    title: "Phone Sales Mastery",
    desc: "The complete APEX phone-selling system — from the verification intro to assuming the sale. Lessons, quizzes, and a certificate.",
    long: "A start-to-finish course on selling life insurance over the phone the APEX way. Work through every stage of the call — mindset, tonality, the verification intro, qualifying questions, objection handling, and the close — then prove it with a short quiz after each module. Finish all six lessons to earn your APEX certificate.",
    date: "May 30, 2026",
    meta: "Course · 6 lessons",
    cta: "Start Course",
    tags: ["course", "phone sales", "objections", "closing", "training"],
    course: {
      instructor: "KJ",
      instructorRole: "Regional Director",
      level: "Core Curriculum",
      learn: [
        "Open every call with a verification intro that holds the line",
        "Control your tonality and pace so the prospect leans in",
        "Ask qualifying questions that build the case for coverage",
        "Handle the price objection without ever dropping the price",
        "Assume the sale and walk the client through the close",
        "Build the daily activity habits that compound into production",
      ],
      modules: [
        {
          title: "The Foundation",
          items: [
            { id: "l1", kind: "lesson", title: "The Mindset of a Closer", media: "video", duration: "8:30",
              blurb: "Why selling is a learnable skill — and the beliefs that separate top producers from everyone else." },
            { id: "l2", kind: "lesson", title: "Owning Your Tonality", media: "audio", duration: "11:15",
              blurb: "Slow down, lower your tone, and let silence do the heavy lifting on every call." },
            { id: "q1", kind: "quiz", title: "Foundations Check", pass: 0.67, questions: [
              { q: "What does KJ say selling fundamentally is?",
                options: ["A learnable skill", "A natural-born talent", "Purely a numbers game", "A matter of luck"], answer: 0 },
              { q: "On a call, your tonality should be:",
                options: ["Fast and high-energy", "Slow and controlled so you own the conversation", "Matched exactly to the prospect", "Loud enough to dominate"], answer: 1 },
              { q: "After you ask a key question, you should:",
                options: ["Keep talking to fill the silence", "Be quiet and let the silence work", "Immediately offer a discount", "Move on quickly"], answer: 1 },
            ] },
          ],
        },
        {
          title: "The Call Framework",
          items: [
            { id: "l3", kind: "lesson", title: "The Verification Intro", media: "video", duration: "9:45",
              blurb: "The benefits-coordinator opener that earns you the next sixty seconds of the call." },
            { id: "l4", kind: "lesson", title: "Qualifying Questions That Sell", media: "video", duration: "12:20",
              blurb: "Surface the income, debt, and dependents that make the right coverage amount obvious." },
            { id: "l5", kind: "lesson", title: "Beating the Price Objection", media: "audio", duration: "10:05",
              blurb: "Reframe “it costs too much” around the value of the protection — and hold your price." },
            { id: "q2", kind: "quiz", title: "Framework Mastery", pass: 0.75, questions: [
              { q: "The purpose of the verification intro is to:",
                options: ["Close the sale immediately", "Earn the next sixty seconds of the call", "Collect payment info", "Ask for referrals"], answer: 1 },
              { q: "Qualifying questions are designed to surface:",
                options: ["The prospect's favorite color", "Income, debt, and dependents", "Competitor pricing", "Nothing — they're small talk"], answer: 1 },
              { q: "When a prospect says “it costs too much,” you should:",
                options: ["Drop the price right away", "Reframe around the value of the protection", "End the call politely", "Repeat the price louder"], answer: 1 },
              { q: "Activity — your dials — is best described as:",
                options: ["Optional once experienced", "What drives your income, with no shortcuts", "Only for slow weeks", "A vanity metric"], answer: 1 },
            ] },
          ],
        },
        {
          title: "The Close",
          items: [
            { id: "l6", kind: "lesson", title: "Assuming the Sale", media: "video", duration: "7:50",
              blurb: "Stop asking for the sale. Start confidently walking the client through it." },
            { id: "q3", kind: "quiz", title: "Certification Exam", pass: 0.8, questions: [
              { q: "The close should be approached by:",
                options: ["Asking “so do you want it?”", "Assuming the sale and walking them through it", "Waiting for the client to bring it up", "Sending a follow-up email"], answer: 1 },
              { q: "Building value before the close means:",
                options: ["Talking about price first", "Establishing the protection's worth so the close is natural", "Rushing to payment", "Skipping the needs analysis"], answer: 1 },
              { q: "A consistent producer relies most on:",
                options: ["One big lucky month", "Coachability and consistency that compound", "Avoiding the phone on slow days", "Memorizing one script forever"], answer: 1 },
              { q: "Repetition, per the trainings, is:",
                options: ["A waste of time", "The mother of skill — drill it until it’s second nature", "Only for new agents", "Less important than talent"], answer: 1 },
              { q: "The right coverage amount becomes obvious when you:",
                options: ["Guess based on age", "Run a needs analysis that surfaces the real gap", "Always sell the cheapest plan", "Let the client decide alone"], answer: 1 },
            ] },
          ],
        },
      ],
    },
  },
  {
    id: "playbook",
    type: "pdf",
    title: "APEX Agent Playbook",
    desc: "The official APEX playbook — your start-to-finish guide to onboarding, daily activity, and the systems that drive production.",
    long: "The complete APEX Agent Playbook: how to get licensed and contracted, set up your tools, run your day, and follow the proven systems that turn new agents into consistent producers. Keep this open in your first 90 days and revisit it often.",
    date: "May 28, 2026",
    meta: "PDF",
    cta: "Open PDF",
    url: "assets/APEX_Agent_Playbook.pdf",
    tags: ["playbook", "onboarding", "getting started", "systems", "guide"],
  },
  {
    id: "needs-quiz",
    type: "pdf",
    title: "Needs Analysis Quiz",
    desc: "A quick client needs-analysis quiz to uncover the real coverage gap before you present.",
    long: "Use this needs-analysis quiz on every appointment to surface income, debt, final-expense, and dependent needs in minutes — so the right coverage amount becomes obvious to the client.",
    date: "May 28, 2026",
    meta: "PDF",
    cta: "Open PDF",
    url: "assets/Needs_Analysis_Quiz.pdf",
    tags: ["needs analysis", "quiz", "discovery", "fact finding", "worksheet"],
  },
  {
    id: "script-3",
    type: "guide",
    title: "Apex Script 3.0 — Senior Benefits",
    desc: "The current Senior State Benefits / life insurance phone script — intro through the close.",
    long: "The latest version of the APEX phone script for senior benefits and life insurance prospects. Covers the verification intro, qualifying questions, and the transition to the presentation. Internalize this before you dial.",
    date: "May 26, 2026",
    meta: "Script · Google Doc",
    cta: "Open Script",
    url: "https://docs.google.com/document/d/1hgA1vKf0Bo0kgQ2nf45bN8tfdLwQMwkWyTbakAjZUKw/edit?usp=sharing",
    tags: ["script", "phone", "senior benefits", "life insurance", "sales"],
  },
  {
    id: "script-vet",
    type: "guide",
    title: "Apex Script — Veterans (VA Benefits)",
    desc: "The veteran burial-coverage opener and full call flow for VA-benefit prospects.",
    long: "The APEX phone script for the veterans market — the benefits-coordinator opener, how to verify existing burial coverage, and the path to a needs analysis. Pairs with the senior benefits script.",
    date: "May 24, 2026",
    meta: "Script · Google Doc",
    cta: "Open Script",
    url: "https://docs.google.com/document/d/1OeDu_6TABfIJtVHrn1TrJUjWGzgehYttoMj7ttSebxI/edit?usp=sharing",
    tags: ["script", "phone", "veterans", "final expense", "sales"],
  },
];

window.APEX_PRESENTERS = [
  { id: "kj",    name: "KJ",    role: "Regional Director", initials: "KJ" },
  { id: "obi",   name: "Obi",   role: "Senior Producer",   initials: "O" },
  { id: "chudi", name: "Chudi", role: "Field Trainer",     initials: "C" },
  { id: "sam",   name: "Sam",   role: "Agency Owner",      initials: "S" },
  { id: "moody", name: "Moody", role: "Top Producer",      initials: "M" },
];

window.APEX_RECORDINGS = [
  { id: "r-obi-1", presenter: "obi", title: "Obi Recording 1", topic: "Training", date: "May 29, 2026", audio: true, video: "https://drive.google.com/file/d/1mzo2RzPyZc1BwLu6-MJDT8VSQoDcRQ7w/preview", desc: "" },
  { id: "r-obi-2", presenter: "obi", title: "Obi Recording 2", topic: "Training", date: "May 29, 2026", audio: true, video: "https://drive.google.com/file/d/1GTV9fIvOMmJKIq_4PsQxy6_IN8UVm-3O/preview", desc: "" },
  { id: "r-obi-3", presenter: "obi", title: "Obi Recording 3", topic: "Training", date: "May 29, 2026", audio: true, video: "https://drive.google.com/file/d/1UfUKBFhBZIRryNAoJpVddvFapJZUwwhp/preview", desc: "" },
  { id: "r-obi-4", presenter: "obi", title: "Obi Recording 4", topic: "Training", date: "May 29, 2026", audio: true, video: "https://drive.google.com/file/d/1v85PsodhALrGRf7BmBVv7AsA1FbD_4Od/preview", desc: "" },
  { id: "r-kj-1", presenter: "kj", title: "Beating the Price Objection — Version 1", topic: "Objections", date: "May 21, 2026", audio: true, video: "https://drive.google.com/file/d/1aNpO39ZqQ3veCp1m4Aya8pa0QQ4Ffzjj/preview", desc: "One version of KJ's price-objection pitch — how he reframes \"it costs too much\" around the value of the protection." },
  { id: "r-kj-2", presenter: "kj", title: "Beating the Price Objection — Version 2", topic: "Objections", date: "May 7, 2026", audio: true, video: "https://drive.google.com/file/d/1Pu3KtI7zg5Bp0uvvHnIhWq7675Kt0Ts6/preview", desc: "A different take on the same price-objection pitch — another way KJ holds the price and moves toward the close." },
  { id: "r-kj-3", presenter: "kj", title: "Selling More Coverage — Objection Handling", topic: "Objections", date: "Apr 12, 2026", audio: true, video: "https://drive.google.com/file/d/1F4QK3vqzTO0R30SKp92KRuDNKhRQf1qj/preview", desc: "Handling objections when positioning additional coverage so clients land on the right level of protection." },
];

window.APEX_QUICKLINKS = [
  { label: "InsuraCloud", sub: "Quoting & e-apps", href: "#" },
  { label: "Readymode", sub: "Power dialer", href: "#" },
  { label: "AgentLink", sub: "Contracting & comp", href: "#" },
  { label: "Website", sub: "apexfinancialempire.com", href: "#" },
];
